### ISSUE TITLE
File Name Too Long Exception

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#22]
Seems to happen at regression test selection stage.

Example Exception:
java.lang.RuntimeException: java.io.FileNotFoundException: /var/jenkins_home/workspace/GeoMap-Parallel-Test/../GeoMap-Parallel-Test_fullPeass/properties_GeoMap-Parallel-Test/methods/011d58f92f2628b4a5e4dee78482fd61d035addd/geomap-backend-objektservice§immo.geomap.backend.objektservice.impl.objekte.TestObjektServiceImpl/createObjekt_java.lang.String_java.lang.String_java.lang.Double_java.lang.Double_java.lang.Boolean_immo.geomap.datamodel.importer.EntryState_immo.geomap.datamodel.objekt.ImmoEinordnungEnums.EKaufMiete_immo.geomap.datamodel.objekt.ImmoEinordnungEnums.EObjektArt_immo.geomap.datamodel.objekt.ImmoEinordnungEnums.EObjektTyp_java.lang.Boolean_int_java.lang.Double_boolean_int_java.lang.Boolean_java.lang.Double_java.time.LocalDateTime_immo.geomap.datamodel.importer.geo.GeoPoint_diff.txt (File name too long)
	at de.dagere.peass.analysis.properties.PropertyReader.readAllTestsProperties(PropertyReader.java:49)
	at de.dagere.peass.ci.ContinuousExecutor.readMethodSources(ContinuousExecutor.java:128)
	at de.dagere.peass.ci.ContinuousExecutor.executeRegressionTestSelection(ContinuousExecutor.java:114)
	at de.dagere.peass.ci.ContinuousExecutor.executeRTS(ContinuousExecutor.java:92)
	at de.dagere.peass.ci.remote.RemoteRTS.invoke(RemoteRTS.java:54)
	at de.dagere.peass.ci.remote.RemoteRTS.invoke(RemoteRTS.java:20)
	at hudson.FilePath.act(FilePath.java:1164)
	at hudson.FilePath.act(FilePath.java:1147)
	at de.dagere.peass.ci.LocalPeassProcessManager.rts(LocalPeassProcessManager.java:57)
	at de.dagere.peass.ci.MeasureVersionBuilder.perform(MeasureVersionBuilder.java:105)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /var/jenkins_home/workspace/GeoMap-Parallel-Test/../GeoMap-Parallel-Test_fullPeass/properties_GeoMap-Parallel-Test/methods/011d58f92f2628b4a5e4dee78482fd61d035addd/geomap-backend-objektservice§immo.geomap.backend.objektservice.impl.objekte.TestObjektServiceImpl/createObjekt_java.lang.String_java.lang.String_java.lang.Double_java.lang.Double_java.lang.Boolean_immo.geomap.datamodel.importer.EntryState_immo.geomap.datamodel.objekt.ImmoEinordnungEnums.EKaufMiete_immo.geomap.datamodel.objekt.ImmoEinordnungEnums.EObjektArt_immo.geomap.datamodel.objekt.ImmoEinordnungEnums.EObjektTyp_java.lang.Boolean_int_java.lang.Double_boolean_int_java.lang.Boolean_java.lang.Double_java.time.LocalDateTime_immo.geomap.datamodel.importer.geo.GeoPoint_diff.txt (File name too long)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2440)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3356)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3340)
	at de.dagere.peass.analysis.properties.MethodChangeReader.readMethodChangeData(MethodChangeReader.java:47)
	at de.dagere.peass.analysis.properties.PropertyReadHelper.readMethodSources(PropertyReadHelper.java:188)
	at de.dagere.peass.analysis.properties.PropertyReadHelper.analyzeTraceFiles(PropertyReadHelper.java:174)
	at de.dagere.peass.analysis.properties.PropertyReadHelper.getSourceInfos(PropertyReadHelper.java:129)
	at de.dagere.peass.analysis.properties.PropertyReadHelper.read(PropertyReadHelper.java:99)
	at de.dagere.peass.analysis.properties.PropertyReader.readMethod(PropertyReader.java:79)
	at de.dagere.peass.analysis.properties.PropertyReader.readVersion(PropertyReader.java:64)
	at de.dagere.peass.analysis.properties.PropertyReader.readAllTestsProperties(PropertyReader.java:43)

**Comment by DaGeRe** [comment]
This should be fixed by https://github.com/DaGeRe/peass/commit/5d2b46d0d2abbd6428e4242d7207631b43da1dc4, can you confirm this?

**Comment by Schattensilber** [comment]
Yep, problem solved.
