### ISSUE TITLE
Treat Test Timeouts better

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#25]
Timeout for tests are a supported feature to cut short unexpectedly long running tests.
Currently they seem to simply lead to an error in the peass process, badly visible for the user. Instead it should inform of the issue clearly and continue running any other tests.

**Comment by DaGeRe** [comment]
Could you provide the stacktrace of the error that occured in the Peass process?

**Comment by Schattensilber** [comment]
Example Exception:
javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; systemId: file:/var/jenkins_home/workspace/GeoMap%20permanent%20long/../GeoMap%20permanent%20long_fullPeass/011d58f92f2628b4a5e4dee78482fd61d035addd_009c2aa2ca09912a8d603f9ddc89e29ae64c1e5c/measurements/immo.geomap.backend.objektservice.impl.objekte.TestObjektServiceImpl/011d58f92f2628b4a5e4dee78482fd61d035addd/011d58f92f2628b4a5e4dee78482fd61d035addd/testSearchPaging_kopeme_1.tmp; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:578)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:264)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189)
	at de.dagere.kopeme.datastorage.XMLDataLoader.loadData(XMLDataLoader.java:72)
	at de.dagere.kopeme.datastorage.XMLDataLoader.<init>(XMLDataLoader.java:49)
	at de.dagere.peass.measurement.analysis.DataReader.readMeasurementFile(DataReader.java:94)
	at de.dagere.peass.measurement.analysis.DataReader.readClassFolder(DataReader.java:82)
	at de.dagere.peass.measurement.analysis.DataReader.readDataToQueue(DataReader.java:58)
	at de.dagere.peass.measurement.analysis.DataReader.access$200(DataReader.java:24)
	at de.dagere.peass.measurement.analysis.DataReader$1.run(DataReader.java:44)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; systemId: file:/var/jenkins_home/workspace/GeoMap%20permanent%20long/../GeoMap%20permanent%20long_fullPeass/011d58f92f2628b4a5e4dee78482fd61d035addd_009c2aa2ca09912a8d603f9ddc89e29ae64c1e5c/measurements/immo.geomap.backend.objektservice.impl.objekte.TestObjektServiceImpl/011d58f92f2628b4a5e4dee78482fd61d035addd/011d58f92f2628b4a5e4dee78482fd61d035addd/testSearchPaging_kopeme_1.tmp; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1473)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
	... 13 more

**Comment by DaGeRe** [comment]
This error seems to consist of two parts:
- If a measurement VM exits unsucessfully (and has time left to write a XML result file, but not to cleanup data), Peass does not recognize the missing measurement data and just goes on.
- Internally, Peass has read every file in the measurement result folder, even leftover temporary files. Therefore, the error occured.

Hopefully, I fixed both with https://github.com/DaGeRe/peass/commit/881fe7a45fa5c24ee796477b0b340e050bfb65fa . Could you try this again with your configuration?

**Comment by DaGeRe** [comment]
The reason for the failure internally was an error in the KoPeMe execution:

> java.lang.RuntimeException: thread waiting for the response was interrupted
>         at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:849)
>         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)
>         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
>         at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1654)
>         at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1639)
>         at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:963)
>         at immo.geomap.tools.elasticsearch.ElasticsearchClient.indexExists(ElasticsearchClient.java:564)
>         at immo.geomap.tools.elasticsearch.ElasticsearchClient.createIndexIfNotExists(ElasticsearchClient.java:699)
>         at immo.geomap.backend.objektservice.impl.objekte.TestObjektServiceImpl.setup(TestObjektServiceImpl.java:83)
>         at sun.reflect.GeneratedMethodAccessor539.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
>         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
>         at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
>         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
>         at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
>         at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
>         at de.dagere.kopeme.junit.rule.KoPeMeRule$1.run(KoPeMeRule.java:52)
>         at de.dagere.kopeme.junit.rule.KoPeMeBasicStatement.runAllRepetitions(KoPeMeBasicStatement.java:165)
>         at de.dagere.kopeme.junit.rule.KoPeMeBasicStatement.runMainExecution(KoPeMeBasicStatement.java:132)
>         at de.dagere.kopeme.junit.rule.KoPeMeStandardRuleStatement.runWarmup(KoPeMeStandardRuleStatement.java:100)
>         at de.dagere.kopeme.junit.rule.KoPeMeStandardRuleStatement.executeSimpleTest(KoPeMeStandardRuleStatement.java:79)
>         at de.dagere.kopeme.junit.rule.KoPeMeStandardRuleStatement.access$000(KoPeMeStandardRuleStatement.java:28)
>         at de.dagere.kopeme.junit.rule.KoPeMeStandardRuleStatement$1.run(KoPeMeStandardRuleStatement.java:45)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.InterruptedException
>         at java.lang.Object.wait(Native Method)
>         at java.lang.Object.wait(Object.java:502)
>         at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:82)
>         at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70)
>         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:279)
>         ... 25 more
> 
Therefore, an integration test should test that after this exception, measurement is continued correctly.
