### ISSUE TITLE
NullPointerException - possibly when no changes found

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#29]
The Exception is:
```
java.lang.NullPointerException
	at de.dagere.peass.ci.rts.RTSVisualizationCreator.readStaticSelection(RTSVisualizationCreator.java:109)
	at de.dagere.peass.ci.rts.RTSVisualizationCreator.visualize(RTSVisualizationCreator.java:46)
	at de.dagere.peass.ci.LocalPeassProcessManager.visualizeRTSResults(LocalPeassProcessManager.java:78)
	at de.dagere.peass.ci.MeasureVersionBuilder.perform(MeasureVersionBuilder.java:114)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```	
Seems to happen when no changes detected.

**Comment by DaGeRe** [comment]
This should be fixed with https://github.com/DaGeRe/peass-ci/commit/11f2367eac5def5cbef1b996bfa89cc2d3c33b9f. Can you confirm this?
