### ISSUE TITLE
JenkinsLogRedirector causes ClassCastException if SimpleLoggerContext is used

### ISSUE THREAD

**Issue by mawHBT** [DaGeRe/peass-ci#36]
If SimpleLoggerContext is used, creating LoggerContext in JenkinsLogRedirector causes:

```
java.lang.ClassCastException: class org.apache.logging.log4j.simple.SimpleLoggerContext cannot be cast to class org.apache.logging.log4j.core.LoggerContext (org.apache.logging.log4j.simple.SimpleLoggerContext and org.apache.logging.log4j.core.LoggerContext are in unnamed module of loader jenkins.util.AntClassLoader @212619ff)
	at de.dagere.peass.ci.JenkinsLogRedirector.<init>(JenkinsLogRedirector.java:14)
	at de.dagere.peass.ci.MeasureVersionBuilder.perform(MeasureVersionBuilder.java:112)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:100)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
```

**Comment by mawHBT** [comment]
It was forgotten to restart Jenkins after the plugin was updated. So an old version was used, which caused the exception.
