### ISSUE TITLE
Logs Missing if Errors Occur

### ISSUE THREAD

**Issue by mawHBT** [DaGeRe/peass-ci#52]
If KiekerFolderUtil.getClazzMethodFolder(KiekerFolderUtil.java:41) throws RuntimeException, no dependency-reading logs are created.

Stacktrace is:
Caused by: java.lang.RuntimeException: Folder $methodResult is no Kieker result folder!
	at de.dagere.peass.dependency.traces.KiekerFolderUtil.getClazzMethodFolder(KiekerFolderUtil.java:41)
	at de.dagere.peass.dependency.DependencyManager.updateDependenciesOnce(DependencyManager.java:221)
	at de.dagere.peass.dependency.DependencyManager.readInitialResultFiles(DependencyManager.java:182)
	at de.dagere.peass.dependency.DependencyManager.initialyGetTraces(DependencyManager.java:116)
	at de.dagere.peass.dependency.reader.InitialVersionReader.readInitialVersion(InitialVersionReader.java:44)
	at de.dagere.peass.dependency.reader.DependencyReader.readInitialVersion(DependencyReader.java:347)
	at de.dagere.peass.ci.ContinuousDependencyReader.doFullyLoadDependencies(ContinuousDependencyReader.java:188)
	at de.dagere.peass.ci.ContinuousDependencyReader.fullyLoadDependencies(ContinuousDependencyReader.java:177)
	at de.dagere.peass.ci.ContinuousDependencyReader.getDependencies(ContinuousDependencyReader.java:111

**Comment by DaGeRe** [comment]
Could you provide the exact error, so I can fix this? (There might be different types of errors, which, in the future, might require different issues).

**Comment by Schattensilber** [comment]
Maybe similar problem, there was an exception, but no logs. Exception was:

```
[org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution [#28]] INFO  de.dagere.peass.ci.ContinuousDependencyReader:174 - Executing regression test selection - Log goes to /var/jenkins_home/workspace/GeoMap permanent daily/../GeoMap permanent daily_fullPeass/rtsLogs/387220fbcc701dc9fd9aa66c1cb2833de9bbae70_5edadf3485d77a902a03363284e13eb56074a239.txt
Exception thrown
java.lang.RuntimeException: java.io.FileNotFoundException: /var/jenkins_home/workspace/GeoMap permanent daily/../GeoMap permanent daily_fullPeass/deps_GeoMap permanent daily.json (No such file or directory)
	at de.dagere.peass.ci.ContinuousDependencyReader.getDependencies(ContinuousDependencyReader.java:125)
	at de.dagere.peass.ci.ContinuousDependencyReader.getTests(ContinuousDependencyReader.java:63)
	at de.dagere.peass.ci.ContinuousExecutor.executeRegressionTestSelection(ContinuousExecutor.java:119)
	at de.dagere.peass.ci.ContinuousExecutor.executeRTS(ContinuousExecutor.java:99)
	at de.dagere.peass.ci.remote.RemoteRTS.invoke(RemoteRTS.java:56)
	at de.dagere.peass.ci.remote.RemoteRTS.invoke(RemoteRTS.java:20)
	at hudson.FilePath.act(FilePath.java:1173)
	at hudson.FilePath.act(FilePath.java:1156)
	at de.dagere.peass.ci.LocalPeassProcessManager.rts(LocalPeassProcessManager.java:67)
	at de.dagere.peass.ci.MeasureVersionBuilder.runAllSteps(MeasureVersionBuilder.java:148)
	at de.dagere.peass.ci.MeasureVersionBuilder.perform(MeasureVersionBuilder.java:120)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /var/jenkins_home/workspace/GeoMap permanent daily/../GeoMap permanent daily_fullPeass/deps_GeoMap permanent daily.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1029)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3495)
	at de.dagere.peass.ci.ContinuousDependencyReader.doFullyLoadDependencies(ContinuousDependencyReader.java:193)
	at de.dagere.peass.ci.ContinuousDependencyReader.fullyLoadDependencies(ContinuousDependencyReader.java:177)
	at de.dagere.peass.ci.ContinuousDependencyReader.getDependencies(ContinuousDependencyReader.java:111)
	... 18 more
```

**Comment by Schattensilber** [comment]
Yes, works for me.

**Comment by mawHBT** [comment]
Works for me also, thank you.
